class AssetPath {
  AssetPath._();
  static const String app_logo = "assets/app_logo.svg";
  static const String bg = "assets/bg.svg";
  static const String bg_image = "assets/bg.png";
  static const String save = "assets/save.svg";
  static const String splashscreen = "assets/splashscreen.svg";
  static const String team = "assets/team.svg";
  static const String timer = "assets/timer.svg";
  static const String viewprofile = "assets/viewprofile.svg";
  static const String warning = "assets/warning.svg";
  static const String wfh = "assets/wfh.svg";
  static const String worklocationimg = "assets/worklocationimg.svg";
  static const String reports = "assets/reports.svg";
  static const String rejected = "assets/rejected.svg";
  static const String pdfnew = "assets/pdfnew.svg";
  static const String officer = "assets/officer.svg";
  static const String office = "assets/office.svg";
  static const String no_uploaded = "assets/no_uploaded.svg";
  static const String leave = "assets/leave.svg";
  static const String in_office = "assets/in_office.svg";
  static const String footer = "assets/footer.svg";
  static const String filter = "assets/filter.svg";
  static const String download = "assets/download.svg";
  static const String down_arrow_new = "assets/down_arrow_new.svg";
  static const String coronavirus = "assets/coronavirus.svg";
  static const String cordinatemasterimg = "assets/cordinatemasterimg.svg";
  static const String coordinate_img = "assets/coordinate_img.svg";
  static const String contacts = "assets/contacts.svg";
  static const String client = "assets/client.svg";
  static const String cancel = "assets/cancel.svg";
  static const String attendance = "assets/attendance.svg";
  static const String approved = "assets/approved.svg";
  static const String approval = "assets/approval.svg";
  //static const String save = "assets/save.svg";
}
