class AppStrings {
  AppStrings._();
  static const String userName = "UserName";
  static const String password = "Password";
  static const String login = "LOGIN";
  static const String loginMobileNo = "LOGIN WITH MOBILE NO.";
  static const String or = "OR";
  static const String mobileNo = "Mobile Number";
  static const String login_username_password = "Login with username and password";
  static const String validate_mpin = "Validate mPin";
  static const String not_you = "Not you?";
  static const String Forgot_mpin = "Forgot mPin?";
  static const String validate = "VALIDATE";
  static const String generate_mpin = "Generate an mPin for your security purpose.";
  static const String confirm_mpin = "Confirm mPin";
  static const String confirm = "CONFIRM"; 
  static const String set_mpin = "Set mPin";
  static const String verification_code = "Verification code";
  static const String verification_code_text = "We have sent the verification code to your Mobile Number";
  static const String resend_otp = "Resend otp";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
}
