class AppStrings {
  AppStrings._();
  static const String UserName = "UserName";
  static const String Password = "Password";
  static const String LOGIN = "LOGIN";
  static const String LOGIN_MOBILE = "LOGIN WITH MOBILE NO.";
  static const String OR = "OR";
  static const String Mobile_Number = "Mobile Number";
  static const String login_username_password = "Login with username and password";
  static const String validate_mpin = "Validate mPin";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
  // static const String ptin_number = "PTIN Number";
}
